/* eslint-disable @typescript-eslint/naming-convention */
// Auto-generated by scripts/sync-product-keys.mjs
// Source: https://raw.githubusercontent.com/mikey0000/PyMammotion/main/pymammotion/utility/device_type.py
// Generated at: 2026-04-07T17:59:08.457Z

export const PRODUCT_KEY_GROUPS = {
    Cm900ProductKey: ['zkRuTK9KsXG', '6DbgVh2Qs5m'],
    Luba2MiniProductKey: ['a1L5ZfJIxGl', 'a1dCWYFLROK'],
    LubaLAProductKey: ['CDYuKXTYrSP'],
    LubaLDProductKey: ['a1jDMfG2Fgj', 'a1vtZq9LUFS'],
    LubaMBProductKey: ['a1pb9toor70'],
    LubaMDProductKey: ['a1T6VTFTc0C', 'a14iRDqMepW'],
    LubaProductKey: ['a1UBFdq6nNz', 'a1x0zHD3Xop', 'a1pvCnb3PPu', 'a1kweSOPylG', 'a1JFpmAV5Ur', 'a1BmXWlsdbA', 'a1jOhAYOIG8', 'a1K4Ki2L5rK', 'a1ae1QnXZGf', 'a1nf9kRBWoH', 'a1ZU6bdGjaM'],
    LubaVAProductKey: ['a1Ce85210Be', 'a1BBOJnnjb9'],
    LubaVProductKey: ['a1iMygIwxFC', 'a1LLmy1zc0j'],
    LubaVProProductKey: ['a1mb8v6tnAa', 'a1pHsTqyoPR'],
    RTKNBProductKey: ['a1NfZqdSREf', 'a1ZuQVL7UiN'],
    RTKProductKey: ['a1qXkZ5P39W', 'a1Nc68bGZzX'],
    YukaMiniProductKey: ['a1BqmEWMRbX', 'a1biqVGvxrE'],
    YukaMLProductKey: ['a1OWGO8WXbh', 'a1s6znKxGvI'],
    YukaMN100ProductKey: ['NnbeYtaEUGE'],
    YukaMVProductKey: ['a1jFe8HzcDb', 'a16cz0iXgUJ', 'USpE46bNTC7', 'pdA6uJrBfjz'],
    YukaPlusProductKey: ['a1lNESu9VST', 'a1zAEzmvWDa'],
    YukaProductKey: ['a1kT0TlYEza', 'a1IQV0BrnXb'],
} as const;

export function resolveProductKeyGroup(productKey: string): string | null {
    if (!productKey) {
        return null;
    }
    for (const [group, keys] of Object.entries(PRODUCT_KEY_GROUPS)) {
        if ((keys as readonly string[]).includes(productKey)) {
            return group;
        }
    }
    return null;
}

export const LUBA_PRO_PRODUCT_KEYS = new Set<string>(PRODUCT_KEY_GROUPS.LubaVProProductKey ?? []);
export const NAVIGATION_RECEIVER_PRODUCT_KEYS = new Set<string>([
    ...(PRODUCT_KEY_GROUPS.LubaVProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaVProProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.Luba2MiniProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaPlusProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMiniProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMVProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMN100ProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMLProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaLAProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaLDProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaVAProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaMDProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaMBProductKey ?? []),
]);
export const YUKA_MINI_PRODUCT_KEYS = new Set<string>(PRODUCT_KEY_GROUPS.YukaMiniProductKey ?? []);
export const YUKA_ML_PRODUCT_KEYS = new Set<string>(PRODUCT_KEY_GROUPS.YukaMLProductKey ?? []);
export const YUKA_PRODUCT_KEYS = new Set<string>([
    ...(PRODUCT_KEY_GROUPS.YukaProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaPlusProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMVProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMN100ProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMiniProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMLProductKey ?? []),
]);

// Mirrors PyMammotion's closed Aliyun product-key list. Unknown keys are
// treated as Mammotion-IoT devices.
export const ALIYUN_PRODUCT_KEYS = new Set<string>([
    ...(PRODUCT_KEY_GROUPS.LubaProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaVProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaVProProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.Luba2MiniProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaPlusProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMiniProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.RTKProductKey ?? []),
    'a1jFe8HzcDb',
    'a16cz0iXgUJ',
    ...(PRODUCT_KEY_GROUPS.LubaLDProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaVAProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.YukaMLProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaMDProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.LubaMBProductKey ?? []),
    ...(PRODUCT_KEY_GROUPS.RTKNBProductKey ?? []),
]);

export function isAliyunProductKey(productKey: string): boolean {
    return !!productKey && ALIYUN_PRODUCT_KEYS.has(productKey);
}
